### ISSUE TITLE
Find more references of example survey questions

### ISSUE THREAD

**Issue by drnikko** [drnikki/diversity-of-the-web#1]
It would be great to see the actual survey questions that other organizations have used to gather their data.  We can add this to the README file.

**Comment by nstielau** [comment]
I put two in the readme at the bottom.  Not amazing, but a good reference, esp. for how to ask some questions.  Maybe we get 4 examples and close this out?

**Comment by drnikko** [comment]
One link 404s and the other is behind a paywall for me.  Can you update?  I'd love to see 4-6 live examples and then yes - let's close out.

**Comment by nstielau** [comment]
Indeed they do.

Just found this too.  Data, not questions, but we can derive some of the classifications: http://www.informationisbeautiful.net/visualizations/diversity-in-tech/

**Comment by nstielau** [comment]
Wikimedia survey guidelines: https://meta.wikimedia.org/wiki/Survey_best_practices#Recommended_services

Amplitude Research questions: http://www.amplituderesearch.com/market-research-questions.shtml

**Comment by nstielau** [comment]
Snap Survey Questions: http://www.snapsurveys.com/blog/5-survey-demographic-question-examples/
