### ISSUE TITLE
Deriving everything from evidence

### ISSUE THREAD

**Issue by rachellawson** [drnikki/diversity-of-the-web#13]
(or, at least, authoritative thinking!)

The irony of a small group of people getting together to work on a diversity survey is they are often not diverse and will choose questions the they “feel” are important to them, personally. I know I do it with gender and sexuality because damn, they are complicated… ;-)

We need to not only base our questions on authoritative lists but also demonstrate why the questions were chosen and how the data collected will be used. It’s only what we would expect from any other survey.

I’ve done a little digging on the subject and come up with this from the UN: http://www.unhcr.org/protection/women/4e7757449/unhcr-age-gender-diversity-policy-working-people-communities-equality-protection.html - it seems to give us a list of:
- age
- beliefs _(presumably, includes but is not restricted to religion?)_
- ethnic background
- nationality
- sexual orientation
- gender identity
- ability
- health
- social status _(really like this one and didn’t think of it before)_
- skill

so maybe our questioning needs to be wider?

**Comment by rachellawson** [comment]
okay, I’m clearly not reading the repo very well today - @imtiffanyyu has it covered with the “big 8” aspects of diversity. It’s perfect and my only comment left to make is we need to describe on the survey what the big 8 are, where the evidence comes from for it and then have the questions

**Comment by imtiffanyyu** [comment]
I know you sent some follow up questions but I haven't had a chance to take
a look yet!

On Wednesday, May 25, 2016, Rachel Lawson notifications@github.com wrote:

> okay, I’m clearly not reading the repo very well today - @imtiffanyyu
> https://github.com/imtiffanyyu has it covered with the “big 8” aspects
> of diversity. It’s perfect and my only comment left to make is we need to
> describe on the survey what the big 8 are, where the evidence comes from
> for it and then have the questions
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/drnikki/diversity-survey/issues/13#issuecomment-221534801

## 

_Tiffany Yu_ | TiffanyYu.com | @ImTiffanyYu http://twitter.com/imtiffanyyu
 | LinkedIn http://www.linkedin.com/in/tiffanyayu
Founder, Diversability http://mydiversability.com

**Comment by drnikko** [comment]
Closing this - I think it's all covered now.
