### ISSUE TITLE
Capture Diversity "Big 8" with Survey Questions

### ISSUE THREAD

**Issue by nstielau** [drnikki/diversity-of-the-web#19]
- [x] Ability - Mental and/or physical
- [x] Age
- [x] Ethnicity
- [x] Gender
- [x] Race
- [x] Religion
- [x] Sexual Orientation
- [x] Socio-Economic Status/Class

**Comment by nstielau** [comment]
@drnikki Do you think Religion is relevant?  I feel like it is less relevant, but also it seems like the "big 8" is an easy framework to follow and would be better to include that have us pick and choose.

**Comment by drnikko** [comment]
@nstielau I think following the framework is a good idea, and just because it isn't a particularly relevant part of my personal identity and life experience, certainly doesn't mean it isn't for others.  I'm with you to just follow the "big 8" and people can decline to answer if it doesn't apply to them.

**Comment by drnikko** [comment]
@rachellawson @imtiffanyyu we've been putting a few of these in.  Do you have any feedback on what's been merged so far?

**Comment by rachellawson** [comment]
@nstielau I think it is relevant, at least. I think we need to expand it more, though, possibly in line with the PR I just made for expression of gender & sexuality? I don’t think it is enough to ask if someone is “in a category” - we need to find out how they express that. 

So, for religion, we need to find out not only if they are “religious” but how it influences their life and work. That’s the interesting bit...

**Comment by rachellawson** [comment]
Also, I've asked a friend to come along (once she has made a gh account) and comment - she has a lot more experience than I do.

**Comment by drnikko** [comment]
EIGHT FOR EIGHT!
