### ISSUE TITLE
Determine the best way to enter/select gender identity

### ISSUE THREAD

**Issue by drnikko** [drnikki/diversity-of-the-web#2]
Many surveys have only the options to select m/f. Those that do provide other options tend to limit the participants responses.

How can we allow people to indicate their gender identity across the spectrum while also maintaining a data format that will be useful for reporting?

**Comment by nstielau** [comment]
Cool.  What about this?

```
Male [] Female [] Transgender [] Other []
```

If we can agree to something and get it into the SURVEY file, we can always iterate from there.

**Comment by rachellawson** [comment]
@jessebeach created a drupal module specifically to address this question - at https://www.drupal.org/project/gender

Which reminds me; I probably need to get her to add me as a co-maintainer now she’s being all laa-de-dah at FB ;-)

**Comment by nstielau** [comment]
Looks like we have a go at this in the survey: https://github.com/drnikki/diversity-survey/blob/master/SURVEY.md#gender-identification

You can make a PR their if you think it should be different. Thx!
