### ISSUE TITLE
Disability/accesability

### ISSUE THREAD

**Issue by thenyouDi** [drnikki/diversity-of-the-web#3]
This issue has a few aspects:
1. We need to allow users to first identify if they identify (sorry this can be re-written) as having a disability.
2. We need to collect data on type/nature of the disability if the answer was "yes"
3. We need to gain insight into how that impacts how they work

**Comment by nstielau** [comment]
@thenyouDi Can you check the SURVEY questions and see if those meet these requests? thx!

**Comment by thenyouDi** [comment]
@nstielau @drnikki I have added a few more questions around this and opened a PR.  I will close this issue out for now.
