### ISSUE TITLE
Where to host results

### ISSUE THREAD

**Issue by nstielau** [drnikki/diversity-of-the-web#34]
We're pretty sure we can find a way to host results this github repo, CSV or otherwise.  If that's not possible we'll consider other options.  Feedback welcome. Thanks!

**Comment by kimby77** [comment]
@nstielau you could create a standalone web page and/or a pdf.

For reference, take a look at this InVision product design report from this year (a high bar :) )

https://www.invisionapp.com/product-design-industry-report-2016

You have to enter your email to get the pdf version

**Comment by nstielau** [comment]
We're doing the survey though getfeedback.com.
We'll host the raw results on github.
