### ISSUE TITLE
promotion

### ISSUE THREAD

**Issue by drnikko** [drnikki/diversity-of-the-web#35]
Need ideas/strategies for survey promotion and distribution.

**Comment by nstielau** [comment]
- Drupal + WordPress Camps organizers (BADcamp, etc)
- Systers, Tech Lady Mafia, DevChix mailing lists
- Women in Drupal twitter
- Pantheon, Acquia, WP-Engine, etc

**Comment by populist** [comment]
What about considering running advertisements to help generate responses to the survey? We may be able to get some advertising donated or could do a small funding campaign to generate funds to do some advertising. This would help mitigate some of the respondent bias.

**Comment by drnikko** [comment]
We're going with populist's idea and running ads to promote the survey itself.  Closing.
