### ISSUE TITLE
How to Assess Leadership?

### ISSUE THREAD

**Issue by populist** [drnikki/diversity-of-the-web#40]
One question that I think the survey would do well to answer is how much diversity is present in the leadership class of organizations (i.e. https://gigaom.com/2014/08/21/eight-charts-that-put-tech-companies-diversity-stats-into-perspective/). 

This could be accomplished by adding qualifications to the "Position" section of the survey or by inclusion of a new section for "Leadership" which asks folks if they are in an executive/leadership role in their organization.

**Comment by drnikko** [comment]
We added a leadership question.  If you want more, open an issue @populist :)
