### ISSUE TITLE
Technical Education vs Non-Technical Education?

### ISSUE THREAD

**Issue by populist** [drnikki/diversity-of-the-web#41]
When looking at educational levels, I think one interesting dimension would be to see if people who work in technology actually have degrees in technical fields. There is lots of research on pipelining into these jobs and getting a sense of how having a CS degree (for example) interacts with our diversity attributes could generate some great insights. 

This could be accomplished by modifying the "Education Level" or adding another section to ask that question specifically.

**Comment by nstielau** [comment]
Anything other than what's in #41?

**Comment by drnikko** [comment]
@populist we added a question for this in: https://github.com/drnikki/diversity-of-the-web/commit/f4f52e2819449cd70ad067dfb008c06b8af000c0 

Reopen if you want more @populist.
