### ISSUE TITLE
Race & Ethnicity and Person of Color Identification

### ISSUE THREAD

**Issue by drnikko** [drnikki/diversity-of-the-web#52]
**On race & ethnicity question:**
1. Do we really need examples of "person of color" labels? 
2. feedback reads:
don't confuse race and ethnicity!

from diffen.com: 
"Race refers to a person's physical characteristics, such as bone structure and skin, hair, or eye color. Ethnicity, however, refers to cultural factors, including nationality, regional culture, ancestry, and language."

this one from PBS clarifies: 
"While race and ethnicity share an ideology of common ancestry, they differ in several ways. First of all, race is primarily unitary. You can only have one race, while you can claim multiple ethnic affiliations. You can identify ethnically as Irish and Polish, but you have to be essentially either black or white."

from Sherri: "Should the question ask for Racial background rather than Ethnicity?"

**On the "do you identify as a person of color" question:**
Question: If you say you are one of the options, do you automatically assume they identify as a "person of color"? You may identify them as a "person of color", they may just call themselves Hispanic.

**Comment by nstielau** [comment]
Addressed some issues.  The survey still does not have a proper question for ethnicity, which I think would be best as a write-in.
