### ISSUE TITLE
Country of origin vs country of residence

### ISSUE THREAD

**Issue by drnikko** [drnikki/diversity-of-the-web#56]
Do we care about the distinction?

**Comment by nstielau** [comment]
I think Country of Residence is more relevant.  On some level they both indicate cultural affiliations, and your immediate context is more relevant.

**Comment by rootwork** [comment]
I think that makes sense too. It might make sense to specify "your country of residence" on that question, as right now it just says "your country."

**Comment by drnikko** [comment]
Closing as fixed. :) Thanks @rootwork !
