### ISSUE TITLE
Content Freeze

### ISSUE THREAD

**Issue by drnikko** [drnikki/diversity-of-the-web#67]
This iteration of the survey will be frozen on Monday, October 17, 2016 so that we can put it into a survey provider and begin to collect survey responses. 

Tagging previous contributors and conversation partners so that you see this and can weigh in: @populist @paulsheldrake @rachellawson @thenyouDi @wweihs @imtiffanyyu @techgirlgeek @rubyji

**Comment by nstielau** [comment]
We are officially frozen!
