### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by rootwork** [drnikki/diversity-of-the-web#69]
Really nitpicking, but just trying to help out:
- The file `CONTIBUTORS` should be `CONTRIBUTORS`, I'm guessing.
- In the second question under religious identification it says "religions person" instead of "religious person".

If anyone else notices any typos, maybe this could be a catchall issue for highlighting them.

**Comment by drnikko** [comment]
Both of these are in - leaving this open if any others come through.  Thanks for the careful proofread, @rootwork!

**Comment by nstielau** [comment]
Woot!
