### ISSUE TITLE
PUBLISHING: Possible survey vendors and examples

### ISSUE THREAD

**Issue by wstocker** [drnikki/diversity-of-the-web#7]
https://www.typeform.com
https://surveyplanet.com
https://www.zoho.com

**Comment by nstielau** [comment]
Wikimedia has some recommended options [1] chosen with privacy and data-transparency in mind. Seem like good options.
- http://www.allourideas.org/
- https://wikimedia.qualtrics.com/ControlPanel/

[1] https://meta.wikimedia.org/wiki/Survey_best_practices#Recommended_services

**Comment by drnikko** [comment]
We're going with getfeedback.com, so closing this.
