### ISSUE TITLE
Religion issue

### ISSUE THREAD

**Issue by fgm** [drnikki/diversity-of-the-web#70]
In its current state, the survey only acknowledges the possibility to be considered a minority for religious persons. 

Actually, agnostics or atheists are often in much more of a minority situation than members of any established religion. The very fact that the survey ignores this shows to which degree it is true.

**Comment by drnikko** [comment]
@FGM Do you have a suggestion for how to reword the question so that it includes atheists and agnostics?

**Comment by fgm** [comment]
I'm not sure what "do you identify as a religious person" will mean to various people, both native and non-native english speakers. I suppose it can be interpreted either someone with an active faith (e.g. attending office, proselytizing, etc), or someone who is a member of secular or regular clergy. Or it can also be interpreted as just someone recognizing being labeled as member of one faith or another. Or also as someone with religion/spirituality being an important part of their life, but not necessarily member of any faith, e.g. an agnostic theologist. The point here being that unlike development-oriented questions, the answers to this question will probably mean different things to different people, and the results would be meaningless when collated, polluting the next question.

Regarding "If you identify as a religious person, do you identify as a minority because of your religion?", I think this could be clearer as "Do you identify as a minority because of your religion or lack thereof?" (without the if...).

**Comment by nstielau** [comment]
@FGM could you look at #73.  Is that an improvement?  Any other recommendations?
